### ISSUE TITLE
I'm not able to run deno cache --lock=deno.lock main.ts in my local

### ISSUE THREAD

**Issue by Rafael-Martins** [armand1m-development/mortybot#13]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Try to install dependencies without pass `--lock-write` like: `deno cache --lock=deno.lock main.ts `

**Error prompt**

![error](https://github.com/armand1m-development/mortybot/assets/27746333/305b8ae4-f171-465f-bf4c-81472c13ed12)

**Expected behavior** 

Run should run normally since I did not change any packages.

**Comment by armand1m** [comment]
this should be fixed now
