### ISSUE TITLE
The session file does not get updated if new sessionData is created

### ISSUE THREAD

**Issue by Rafael-Martins** [armand1m-development/mortybot#5]
I created a new sessionDataInitializer and it was not being initialized then I manually erased the session file and the session was initialized and properly injected in the ctx

**Comment by armand1m** [comment]
yup that happens when we add new features to the session and a chat that was using the bot before that feature was there tries to use it

there is this migrations feature in grammy, but we're not leveraging it yet https://grammy.dev/plugins/session.html#migrations

but perhaps we should

**Comment by armand1m** [comment]
now migrations are a thing and implemented in production, although not really ready for too many extensions, there is a way to make it happen. refer to this PR for an example https://github.com/armand1m-development/mortybot/pull/10/files#diff-25c4fb207df4a5b530bba3e81fcef6c34aa34403f96b7f0e7b9c4741a233fcdfR43

**Comment by Rafael-Martins** [comment]
Nice, thanks for the reply!
